import { Scene3D } from './scene3d.js?v=interior-6';

const canvas=document.getElementById('gameCanvas'),view=new Scene3D(canvas);
const ui={phase:document.getElementById('phaseLabel'),damage:document.getElementById('damageLabel'),trust:document.getElementById('trustLabel'),budget:document.getElementById('budgetLabel'),seed:document.getElementById('seedLabel'),objective:document.getElementById('objective'),instruction:document.getElementById('instruction'),caption:document.getElementById('canvasCaption'),primary:document.getElementById('primaryAction'),diagnosis:document.getElementById('diagnosisPanel'),tools:document.getElementById('toolsPanel'),inventory:document.getElementById('inventoryLabel'),evidenceCount:document.getElementById('evidenceCount'),log:document.getElementById('eventLog'),modal:document.getElementById('resultModal'),resultGrade:document.getElementById('resultGrade'),resultTitle:document.getElementById('resultTitle'),resultSummary:document.getElementById('resultSummary'),resultStats:document.getElementById('resultStats'),sound:document.getElementById('soundToggle'),share:document.getElementById('shareButton'),shareStatus:document.getElementById('shareStatus')};
const rooms={attic:{label:'ATTIC'},nursery:{label:'NURSERY'},hall:{label:'UPSTAIRS HALL'},garage:{label:'GARAGE'},kitchen:{label:'KITCHEN'},outside:{label:'FRONT YARD / ENTRY'}};
const graph={attic:['nursery','garage'],nursery:['attic','hall'],hall:['nursery','kitchen','garage'],garage:['attic','hall','kitchen'],kitchen:['hall','garage','outside'],outside:[]};
const evidence=[{id:'tracks',title:'Hand-like tracks',detail:'Five long toes in the insulation. Much larger than rat prints.'},{id:'fur',title:'Coarse dark fur',detail:'Caught on the ceiling crack beneath the attic.'},{id:'soffit',title:'Pried soffit',detail:'The aluminum edge was pulled outward by something dexterous.'},{id:'sound',title:'Heavy night movement',detail:'A slow thump-scrape after midnight, not light daytime skittering.'}];
const phaseNames={briefing:'Briefing',investigate:'Investigation',diagnose:'Diagnosis',prepare:'Preparation',contain:'Live containment',closeout:'Repair & cleanup',resolved:'Job complete'},phaseOrder=['briefing','investigate','diagnose','prepare','contain','closeout'],costs={trap:55,barrier:25,seal:35,clean:30};
const jobSeed=(new URLSearchParams(location.search).get('seed')||'0147').slice(0,24);let state,audioContext,soundEnabled=true;

function hashSeed(value){let hash=2166136261;for(const char of value){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return hash>>>0||1;}
function seededRandom(){state.rngState=(state.rngState+0x6D2B79F5)>>>0;let value=state.rngState;value=Math.imul(value^value>>>15,value|1);value^=value+Math.imul(value^value>>>7,value|61);return((value^value>>>14)>>>0)/4294967296;}
function playCue(type){if(!soundEnabled)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime,gain=audioContext.createGain(),osc=audioContext.createOscillator(),cue={inspect:[520,.08,'sine'],select:[310,.06,'triangle'],start:[120,.28,'sawtooth'],step:[150,.09,'triangle'],breach:[70,.42,'square'],capture:[660,.32,'sine'],repair:[430,.16,'triangle'],clean:[760,.2,'sine'],fail:[90,.5,'sawtooth']}[type]||[300,.08,'sine'];osc.frequency.setValueAtTime(cue[0],now);osc.type=cue[2];gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.12,now+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+cue[1]);osc.connect(gain).connect(audioContext.destination);osc.start(now);osc.stop(now+cue[1]+.02);}catch{soundEnabled=false;ui.sound.setAttribute('aria-pressed','false');ui.sound.textContent='Sound unavailable';}}
function freshState(){return{phase:'briefing',selectedTool:'inspect',found:[],diagnosis:null,seed:jobSeed,rngState:hashSeed(jobSeed),decisionCount:0,traps:[],barriers:[],damage:0,trust:100,budget:240,animal:{room:'attic',previous:null,stress:10,captured:false,escaped:false,moving:false,from:'attic',to:'attic',moveStart:0,moveDuration:1100},simStarted:0,nextDecision:0,incidents:{nursery:false,kitchen:false},closeout:{seal:false,clean:false},log:[{time:'22:14',text:`Dispatch: heavy attic noise, damaged soffit. Job seed ${jobSeed}.`}],resolved:false};}
function reset(){state=freshState();ui.modal.hidden=true;ui.caption.textContent='Customer reports heavy scratching above the second floor after midnight.';updateUI();}
function log(text){const active=['contain','closeout'].includes(state.phase),seconds=active&&state.simStarted?Math.floor((performance.now()-state.simStarted)/1000):0;state.log.unshift({time:seconds?`+${String(seconds).padStart(2,'0')}s`:'22:—',text});state.log=state.log.slice(0,12);}
function setPhase(phase){state.phase=phase;updateUI();}
function inspectClue(id){const item=evidence.find(clue=>clue.id===id);if(!item||state.phase!=='investigate'||state.found.includes(item.id))return;state.found.push(item.id);log(`${item.title}: ${item.detail}`);ui.caption.textContent=item.detail;playCue('inspect');if(state.found.length===2)log('Enough evidence to log a diagnosis. More clues improve confidence.');updateUI();}
function chooseDiagnosis(species){if(state.phase!=='diagnose')return;state.diagnosis=species;playCue('select');if(species==='raccoon'){log('Diagnosis confirmed: raccoon. Use a sturdy live trap and control its escape route.');state.trust=Math.min(100,state.trust+2);}else{log(`Diagnosis logged as ${species}. The evidence does not fit; the attic animal is already agitated.`);state.trust-=10;state.animal.stress=38;}state.selectedTool='trap';setPhase('prepare');}

function placeContainmentTool(roomId){
  if(roomId==='outside'||(roomId==='attic'&&state.selectedTool==='barrier')){ui.caption.textContent=roomId==='outside'?'The yard cannot hold containment equipment.':'You cannot seal the animal inside the attic.';return;}
  if(state.selectedTool==='trap'){
    if(state.phase==='contain'){ui.caption.textContent='The trap cannot be moved while the animal is loose.';return;}
    if(state.traps[0]===roomId){state.traps=[];state.budget+=costs.trap;log('Live trap returned to the van.');}
    else if(state.traps.length){const from=rooms[state.traps[0]].label.toLowerCase();state.traps=[roomId];log(`Live trap moved from ${from} to ${rooms[roomId].label.toLowerCase()}.`);}
    else{if(state.budget<costs.trap)return;state.traps=[roomId];state.budget-=costs.trap;log(`Live trap armed in ${rooms[roomId].label.toLowerCase()}.`);}
    ui.caption.textContent=roomId==='garage'?'Good: quiet, near the attic route, and away from occupants.':'Bait helps, but an open escape route may still look safer.';playCue('select');
  }else if(state.selectedTool==='barrier'){
    if(state.barriers.includes(roomId)){if(state.phase==='contain'){ui.caption.textContent='Do not pull a barrier while the animal is loose.';return;}state.barriers=state.barriers.filter(id=>id!==roomId);state.budget+=costs.barrier;log(`Barrier removed from ${rooms[roomId].label.toLowerCase()}.`);playCue('select');}
    else{if(state.barriers.length>=3){ui.caption.textContent='All three temporary barriers are deployed.';return;}if(state.animal.room===roomId&&state.phase==='contain'){ui.caption.textContent='Too late—the raccoon is already in that room.';return;}if(state.budget<costs.barrier)return;state.barriers.push(roomId);state.budget-=costs.barrier;log(`${state.phase==='contain'?'Emergency b':'B'}arrier placed across ${rooms[roomId].label.toLowerCase()} route.`);playCue('select');}
  }updateUI();
}
function performCloseout(roomId){const cleanRoom=state.incidents.nursery?'nursery':'attic';if(state.selectedTool==='seal'){if(roomId!=='outside'){ui.caption.textContent='The pried soffit entry is outside above the porch.';return;}if(state.closeout.seal){ui.caption.textContent='The soffit entry is already sealed.';return;}if(state.budget<costs.seal)return;state.closeout.seal=true;state.budget-=costs.seal;state.trust=Math.min(100,state.trust+5);log('ENTRY SEALED: mesh and flashing secured over the pried soffit. Trust +5.');playCue('repair');state.selectedTool=state.closeout.clean?'seal':'clean';}else if(state.selectedTool==='clean'){if(roomId!==cleanRoom){ui.caption.textContent=`Contamination is concentrated in the ${rooms[cleanRoom].label.toLowerCase()}.`;return;}if(state.closeout.clean){ui.caption.textContent='The contaminated area is already cleaned.';return;}if(state.budget<costs.clean)return;state.closeout.clean=true;state.budget-=costs.clean;state.trust=Math.min(100,state.trust+5);log(`AREA CLEANED: HEPA vacuum and disinfectant used in ${rooms[cleanRoom].label.toLowerCase()}. Trust +5.`);playCue('clean');state.selectedTool=state.closeout.seal?'clean':'seal';}updateUI();}
function placeTool(roomId){if(['prepare','contain'].includes(state.phase))placeContainmentTool(roomId);else if(state.phase==='closeout')performCloseout(roomId);}
function startContainment(){if(state.phase!=='prepare')return;if(!state.traps.length){ui.caption.textContent='Place the live trap before disturbing the attic.';return;}state.phase='contain';state.simStarted=performance.now();state.nextDecision=state.simStarted+1050;log('Containment started. Footsteps in the attic—watch the route and be ready to react.');ui.caption.textContent='SCRATCH—THUMP. The raccoon is choosing a way out.';playCue('start');updateUI();}
function scoreDestination(from,id){let score=0;if(id==='outside')score+=125;if(id==='nursery')score+=from==='attic'?62:10;if(id==='hall')score+=38;if(id==='kitchen')score+=58;if(id==='garage')score+=18;if(state.traps.includes(id))score+=state.diagnosis==='raccoon'?35:8;if(id===state.animal.previous)score-=36;if(id==='nursery'&&state.incidents.nursery)score-=8;return score+Math.min(24,state.animal.stress*.25);}
function makeDecision(now){const a=state.animal,options=graph[a.room].filter(id=>!state.barriers.includes(id));if(!options.length){state.damage+=90;state.trust-=18;a.stress+=22;log(`Cornered in ${rooms[a.room].label.toLowerCase()}: clawing damages trim while the raccoon searches again.`);if(state.barriers.length){const failed=state.barriers.pop();log(`The ${rooms[failed].label.toLowerCase()} barrier buckles under pressure.`);}state.nextDecision=now+1250;playCue('breach');updateUI();return;}const ranked=options.map(id=>({id,score:scoreDestination(a.room,id)+seededRandom()*6}));ranked.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));const target=ranked[0].id;state.decisionCount++;a.previous=a.room;a.from=a.room;a.to=target;a.moving=true;a.moveStart=now;ui.caption.textContent=`Movement: ${rooms[a.room].label.toLowerCase()} → ${rooms[target].label.toLowerCase()}.`;playCue('step');}
function beginCloseout(){state.phase='closeout';state.selectedTool='seal';log('ANIMAL SECURED: transfer cage latched. Seal the entry and clean contamination before submitting the job.');ui.caption.textContent='Capture complete. Patch the porch soffit and decontaminate the affected room.';playCue('capture');updateUI();}
function finishMove(now){const a=state.animal;a.room=a.to;a.moving=false;a.stress+=8;if(a.room==='nursery'&&!state.incidents.nursery){state.incidents.nursery=true;state.damage+=180;state.trust-=22;log('CEILING BREACH: the raccoon drops into the occupied nursery. Damage +$180, trust −22.');ui.caption.textContent='It broke through the nursery ceiling. Block the kitchen while it is still upstairs.';playCue('breach');}if(a.room==='kitchen'&&!state.incidents.kitchen){state.incidents.kitchen=true;state.damage+=125;state.trust-=16;log('KITCHEN RAID: food and dishes hit the floor. Damage +$125, trust −16.');playCue('breach');}if(state.traps.includes(a.room)){if(state.diagnosis==='raccoon'){a.captured=true;log(`Trap secured in ${rooms[a.room].label.toLowerCase()}.`);beginCloseout();return;}state.traps=[];state.damage+=35;state.trust-=8;a.stress+=22;log('WRONG-SIZE TRAP: the door snaps early. The animal bolts; damage +$35, trust −8.');playCue('breach');}if(a.room==='outside'){a.escaped=true;log('The raccoon reaches the front walk and disappears into the neighborhood.');resolve(false);return;}if(state.damage>=650||state.trust<=0){log('The customer stops the job after escalating damage.');resolve(false);return;}state.nextDecision=now+(a.room==='nursery'?3000:1050);updateUI();}

function stat(label,value){const box=document.createElement('div'),small=document.createElement('small'),strong=document.createElement('strong');small.textContent=label;strong.textContent=value;box.append(small,strong);return box;}
function resolve(captured){state.phase='resolved';state.resolved=true;const trust=Math.max(0,state.trust),complete=state.closeout.seal&&state.closeout.clean;let grade=captured&&complete?(state.damage===0&&trust>=95?'A':state.damage<250&&trust>=60?'B':'C'):'D';if(!captured&&trust<35)grade='F';const jobValue=Math.max(0,(captured?420:90)-state.damage-Math.max(0,240-state.budget));ui.resultGrade.textContent=grade;ui.resultTitle.textContent=captured?'Job completed':'Animal escaped';ui.resultSummary.textContent=captured?(state.incidents.nursery?'You recovered containment, removed the animal, and finished the property work. The ceiling damage still reduced the invoice.':'Diagnosis, containment, exclusion, and cleanup all held together. Mrs. Alvarez can sleep in the house tonight.'):'The route stayed open through the house. Follow the field log backward, change the preparation, and try the same seed again.';ui.resultStats.replaceChildren(stat('Damage',`$${state.damage}`),stat('Trust',String(trust)),stat('Job value',`$${jobValue}`));updateUI();if(!captured)playCue('fail');setTimeout(()=>{ui.modal.hidden=false;document.getElementById('modalRestart').focus();},450);}
function setTool(tool){const allowed=(tool==='inspect'&&state.phase==='investigate')||(['trap','barrier'].includes(tool)&&['prepare','contain'].includes(state.phase))||(['seal','clean'].includes(tool)&&state.phase==='closeout');if(!allowed)return;state.selectedTool=tool;playCue('select');updateUI();}
function renderLog(){const items=state.log.map(item=>{const li=document.createElement('li'),strong=document.createElement('strong');strong.textContent=item.time;li.append(strong,document.createTextNode(` — ${item.text}`));return li;});ui.log.replaceChildren(...items);}
function updateUI(){ui.phase.textContent=phaseNames[state.phase];ui.damage.textContent=`$${state.damage}`;ui.trust.textContent=Math.max(0,state.trust);ui.budget.textContent=`$${state.budget}`;ui.seed.textContent=state.seed;const closeDone=Number(state.closeout.seal)+Number(state.closeout.clean);ui.evidenceCount.textContent=state.phase==='closeout'?`${closeDone} / 2 tasks`:`${state.found.length} / ${evidence.length} clues`;ui.inventory.textContent=state.phase==='closeout'?`Entry ${state.closeout.seal?'sealed':'open'} · Area ${state.closeout.clean?'clean':'contaminated'}`:`Trap ${state.traps.length}/1 · Barriers ${state.barriers.length}/3 · tap placed gear to undo`;renderLog();ui.diagnosis.hidden=state.phase!=='diagnose';ui.tools.hidden=!['investigate','prepare','contain','closeout'].includes(state.phase);ui.primary.hidden=false;ui.primary.disabled=false;
  const copy={briefing:['Review the call','Mrs. Alvarez heard heavy movement above the nursery after midnight. Enter through the porch, inspect the house, and use the garage ladder to reach the attic.','Accept job'],investigate:['Collect evidence','Walk close to amber evidence and tap it. Use E or tap the ladder prompt in the garage to reach the attic.',state.found.length>=2?'Log diagnosis':`Find ${2-state.found.length} more clue${state.found.length===1?'':'s'}`],diagnose:['Name the animal','Compare the clues, then commit. A wrong diagnosis means the wrong trap setup.','Choose a species below'],prepare:['Shape a safe route','Carry the selected tool into a room, then tap its floor or sign to place it.','Start containment'],contain:['Contain and recover','The glowing orange arc is the committed move. Move through the house to place emergency barriers.','Containment active'],closeout:['Finish the property work',`The animal is secure. Walk to the porch soffit and clean the ${state.incidents.nursery?'nursery':'attic'} before leaving.`,closeDone===2?'Submit completed job':`Complete ${2-closeDone} more task${closeDone===1?'':'s'}`],resolved:['Job closed','Review the event chain, share the seed, or run another call.','Job complete']}[state.phase];[ui.objective.textContent,ui.instruction.textContent,ui.primary.textContent]=copy;if(state.phase==='investigate'&&state.found.length<2)ui.primary.disabled=true;if(['diagnose','contain','resolved'].includes(state.phase))ui.primary.disabled=true;if(state.phase==='closeout'&&closeDone<2)ui.primary.disabled=true;document.querySelectorAll('[data-tool]').forEach(btn=>{const tool=btn.dataset.tool,allowed=(tool==='inspect'&&state.phase==='investigate')||(['trap','barrier'].includes(tool)&&['prepare','contain'].includes(state.phase))||(['seal','clean'].includes(tool)&&state.phase==='closeout');btn.disabled=!allowed;btn.classList.toggle('selected',tool===state.selectedTool);});document.querySelectorAll('[data-species]').forEach(btn=>btn.classList.toggle('selected',btn.dataset.species===state.diagnosis));const currentIndex=state.phase==='resolved'?phaseOrder.length:phaseOrder.indexOf(state.phase);document.querySelectorAll('#phaseTrack [data-phase]').forEach((item,index)=>{item.classList.toggle('done',index<currentIndex);item.classList.toggle('active',index===currentIndex);});}

view.setHandlers({
  onEvidence:inspectClue,
  onRoom:roomId=>{if(['prepare','contain','closeout'].includes(state.phase))placeTool(roomId);},
  onTooFar:type=>{ui.caption.textContent=type==='evidence'?'Walk closer to inspect that evidence.':'Enter the room before using equipment there.';},
  onLadder:result=>{ui.caption.textContent=result==='up'?'You climb into the attic. Watch your footing around the joists.':result==='down'?'You climb back down into the garage.':'The attic ladder is in the rear of the garage. Walk closer first.';}
});
document.querySelectorAll('[data-move]').forEach(button=>{
  const release=()=>view.setMoveKey(button.dataset.move,false);
  button.addEventListener('pointerdown',event=>{event.preventDefault();view.setMoveKey(button.dataset.move,true);});
  button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('pointerleave',release);
  button.addEventListener('click',()=>view.nudge(button.dataset.move));
});
document.getElementById('climbButton').addEventListener('click',()=>view.useLadder());
ui.primary.addEventListener('click',()=>{if(state.phase==='briefing'){playCue('select');setPhase('investigate');}else if(state.phase==='investigate'&&state.found.length>=2)setPhase('diagnose');else if(state.phase==='prepare')startContainment();else if(state.phase==='closeout'&&state.closeout.seal&&state.closeout.clean)resolve(true);});
document.querySelectorAll('[data-species]').forEach(button=>button.addEventListener('click',()=>chooseDiagnosis(button.dataset.species)));document.querySelectorAll('[data-tool]').forEach(button=>button.addEventListener('click',()=>setTool(button.dataset.tool)));document.getElementById('restartButton').addEventListener('click',reset);document.getElementById('modalRestart').addEventListener('click',reset);document.getElementById('newSeedButton').addEventListener('click',()=>{location.search=`?seed=${Date.now().toString(36)}`;});
ui.sound.addEventListener('click',()=>{soundEnabled=!soundEnabled;ui.sound.setAttribute('aria-pressed',String(soundEnabled));ui.sound.textContent=soundEnabled?'Sound on':'Sound off';if(soundEnabled)playCue('select');});ui.share.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);ui.share.textContent='Link copied';ui.shareStatus.textContent=`Copied this seeded job: ${state.seed}`;setTimeout(()=>ui.share.textContent='Copy job link',1800);}catch{ui.shareStatus.textContent=`Share this URL: ${location.href}`;}});
window.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='r')reset();if(['1','2','3','4','5'].includes(event.key))setTool(['','inspect','trap','barrier','seal','clean'][Number(event.key)]);if(event.code==='Space'&&state.phase==='prepare'){event.preventDefault();startContainment();}});
function frame(now){if(state.phase==='contain'&&!state.animal.moving&&now>state.nextDecision)makeDecision(now);if(state.phase==='contain'&&state.animal.moving&&now-state.animal.moveStart>=state.animal.moveDuration)finishMove(now);view.render(now,state);requestAnimationFrame(frame);}reset();requestAnimationFrame(frame);
